# Generated by Django 4.2.4 on 2023-12-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Job_Model',
        ),
    ]
