# Generated by Django 4.2.4 on 2023-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_job_job_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
